// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgAoGt8A0sBvvWas0B1VGsdrrFTqlYu88',
    appId: '1:626464651654:web:1a9aaceff266cde40d1407',
    messagingSenderId: '626464651654',
    projectId: 'wtf-flutter-test-c72f2',
    authDomain: 'wtf-flutter-test-c72f2.firebaseapp.com',
    storageBucket: 'wtf-flutter-test-c72f2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEs2DjMK44akbSZGVyWUjMEq8NIcG18K0',
    appId: '1:626464651654:android:4d32afc7adb5b9a80d1407',
    messagingSenderId: '626464651654',
    projectId: 'wtf-flutter-test-c72f2',
    storageBucket: 'wtf-flutter-test-c72f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACpRDrO5Yh2ZnBvuJyhdPoAScVi34dck4',
    appId: '1:626464651654:ios:253cce8db4eecb790d1407',
    messagingSenderId: '626464651654',
    projectId: 'wtf-flutter-test-c72f2',
    storageBucket: 'wtf-flutter-test-c72f2.firebasestorage.app',
    iosBundleId: 'com.example.trainerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACpRDrO5Yh2ZnBvuJyhdPoAScVi34dck4',
    appId: '1:626464651654:ios:253cce8db4eecb790d1407',
    messagingSenderId: '626464651654',
    projectId: 'wtf-flutter-test-c72f2',
    storageBucket: 'wtf-flutter-test-c72f2.firebasestorage.app',
    iosBundleId: 'com.example.trainerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgAoGt8A0sBvvWas0B1VGsdrrFTqlYu88',
    appId: '1:626464651654:web:2bf5f369ddb7aabb0d1407',
    messagingSenderId: '626464651654',
    projectId: 'wtf-flutter-test-c72f2',
    authDomain: 'wtf-flutter-test-c72f2.firebaseapp.com',
    storageBucket: 'wtf-flutter-test-c72f2.firebasestorage.app',
  );
}
